### ISSUE TITLE
Installation is failing on YunoHost 2.7.10 (stable)

### ISSUE THREAD

**Issue by ozbek** [YunoHost-Apps/weblate_ynh#8]
Running on Raspberry Pi. 

Seems like installation is failing at [`weblate migrate --noinput`](https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/install#L233).

Traceback (please read from bottom to top):
```
ImportError: No module named phply.phpparse
from phply.phpparse import make_parser
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/translate/storage/php.py", line 63, in
from translate.storage import php, po
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/translate/convert/po2php.py", line 31, in
from translate.convert import po2php
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/formats.py", line 37, in
from weblate.trans.formats import FILE_FORMAT_CHOICES, FILE_FORMATS, ParseError
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/models/subproject.py", line 42, in
from weblate.trans.models.subproject import SubProject
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/models/__init__.py", line 36, in
__import__(name)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
self.models_module = import_module(models_module_name)
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
app_config.import_models()
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
apps.populate(settings.INSTALLED_APPS)
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
django.setup()
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
utility.execute()
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
execute_from_command_line(argv)
File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/runner.py", line 33, in main
load_entry_point('Weblate==2.17.1', 'console_scripts', 'weblate')()
File "/var/www/weblate/venv/bin/weblate", line 9, in
Traceback (most recent call last):
+ weblate migrate --noinput
```

**Comment by Jibec** [comment]
hi, thanks for your report, I indeed noticed the CI told me the same error.

Can you please try the install from github?

`sudo yunohost app install https://github.com/YunoHost-Apps/weblate_ynh/` (or use the web interface and paste this URL)

**Comment by Jibec** [comment]
please reopen this if you still have an issue

**Comment by ozbek** [comment]
Installing from web interface did not work (encountered the same error). Will try the command line later...

**Comment by Jibec** [comment]
Did you used the installation from git in the web interface?
-- 
Jean-Baptiste Holcroft

**Comment by ozbek** [comment]
No, I was using the one from the community list...

Installing from shell went through OK, but then could not map the existing users with weblate instance. So then uninstalled that instance and re-installed using the [link](https://github.com/YunoHost-Apps/weblate_ynh/) you gave above from the admin interface. Installation went through fine, but still can not login with the existing yunohost users.

**Comment by Jibec** [comment]
Good, so the issue is fixed, please open a new issue for user connexion (technical word is: LDAP integration) so I answer at the correct place ;)
